[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
srun: error: gpu15: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 154, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
srun: error: gpu15: tasks 1-3: Exited with exit code 1
srun: error: gpu16: tasks 4-5,7: Exited with exit code 1
srun: error: gpu16: task 6: Exited with exit code 1
